version: '3.8'

services:
  frontend:
    build: 
      context: ./Trials_of_Chaos
      dockerfile: dockerfile
      args:
        - VITE_UXMAL=/api
      target: nginx
    ports:
      - "80:80"
    image: trials-of-chaos-frontend
    networks:
      - chaos-network
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

  backend:
    build:
      context: ./Uxmal
    image: trials-of-chaos-backend
    ports:
      - "3500:3500"
    networks:
      - chaos-network
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - port_=3500
      - CORS_ORIGIN=http://frontend

  mysql:
    image: mysql:8
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Uxmal/schemas/modifiers.sql:/docker-entrypoint-initdb.d/01-init-modifiers.sql
      - ./Uxmal/schemas/monsters.sql:/docker-entrypoint-initdb.d/02-init-monsters.sql
      - ./Uxmal/schemas/affixes.sql:/docker-entrypoint-initdb.d/03-init-affixes.sql
      - ./Uxmal/schemas/items.sql:/docker-entrypoint-initdb.d/04-init-items.sql
    networks:
      - chaos-network
    restart: unless-stopped
    ports:
      - "3307:3306"

volumes:
  mysql-data:

networks:
  chaos-network:
    driver: bridge