FROM node:22-slim AS base
WORKDIR /Trials_of_Chaos
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

FROM base AS dev
COPY . .
EXPOSE 5173
CMD ["pnpm", "run", "dev"]

FROM base AS production
COPY . .
ARG VITE_UXMAL=/api
ENV VITE_UXMAL=${VITE_UXMAL}
RUN pnpm build
FROM nginx:stable-alpine AS nginx
RUN apk add --no-cache bash
COPY --from=production /Trials_of_Chaos/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]