    CREATE DATABASE IF NOT EXISTS modifiers;
    USE modifiers;
    
    CREATE TABLE modifiers (
        id INT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        stages INT NOT NULL,
        stage1 BOOLEAN NOT NULL,
        stage2 BOOLEAN NOT NULL,
        stage3 BOOLEAN NOT NULL,
        description1 TEXT NOT NULL,
        description2 TEXT,
        description3 TEXT,
        active BOOLEAN NOT NULL,
        imgurl TEXT NOT NULL
    );

    INSERT INTO modifiers (id, name, stages, stage1, stage2, stage3, description1, description2, description3, active, imgurl) VALUES
    (1, 'Blood Globules', 2, TRUE, TRUE, False, 
     'Globules of blood manifest nearby, tracking you. When above you they will fall, dealing Physical damage', 
     'Globules of blood manifest nearby, tracking you. When above you they will fall, dealing Physical damage and creating damaging blood ground', 
     '', 
     TRUE, 
     'https://www.poe2wiki.net/images/b/b8/Blood_Globules_Ultimatum.png'),
    (2, 'Blood Mist', 1, TRUE, False, False, 
     'Challenge area is enshrouded by a blood mist which makes monsters within it immune to damage', 
     '', 
     '', 
     False, 
     'https://www.poe2wiki.net/images/7/77/Blood_Mist_Ultimatum.png'),
    (3, 'Burning Turrets', 2, TRUE, False, False, 
     'Challenge area contains turrets that will periodically fire Fire Projectiles ahead', 
     'Challenge area contains turrets that will periodically fire barrages of Fire Projectiles ahead', 
     '', 
     TRUE, 
     'https://www.poe2wiki.net/images/0/0a/Burning_Turrets_Ultimatum.png'),
    (4, 'Chaotic Monsters', 2, TRUE, TRUE, False, 
     'Monsters gain 20% of damage added as extra Chaos damage', 
     'Monsters gain 50% of damage added as extra Chaos damage', 
     '', 
     TRUE, 
     'https://www.poe2wiki.net/images/9/96/Chaotic_Monsters_Ultimatum.png'),
    (5, 'Deadly Monsters', 2, TRUE, TRUE, False, 
     'Monsters have 300% increased Critical Hit Chance', 
     'Monsters always deal Critical Hits', 
     '', 
     TRUE, 
     'https://www.poe2wiki.net/images/7/76/Deadly_Monsters_Ultimatum.png'),
    (6, 'Damaged Defences', 2, TRUE, TRUE, False, 
     '40% less Defences', 
     '75% less Defences', 
     '', 
     TRUE, 
     'https://www.poe2wiki.net/images/2/27/Damaged_Defences_Ultimatum.png'),
    (7, 'Drought', 1, TRUE, False, False, 
     'Monsters grant no Flask and Charm Charges on death', 
     '', 
     '', 
     TRUE, 
     'https://www.poe2wiki.net/images/9/9f/Drought_Ultimatum.png'),
    (8, 'Enraged Bosses', 1, TRUE, False, False, 
     'Runes will appear that will call deadly Lightning storms if you remain in them', 
     '', 
     '', 
     TRUE, 
     'https://www.poe2wiki.net/images/6/67/Enraged_Bosses_Ultimatum.png'),
    (9, 'Entangling Monsters', 1, TRUE, False, False, 
     'Monsters inflict Grasping Vines on Hit', 
     '', 
     '', 
     TRUE, 
     'https://www.poe2wiki.net/images/b/b1/Entangling_Monsters_Ultimatum.png'),
    (10, 'Escalating Damage', 1, TRUE, False, False, 
     'In each encounter room, damage taken will slowly increase by 1% per second, up to 50%', 
     '', 
     '', 
     TRUE, 
     'https://www.poe2wiki.net/images/6/63/Escalating_Damage_Taken_Ultimatum.png'),
    (11, 'Heart Tethers', 2, TRUE, TRUE, False, 
     'Bloody hearts appear that apply tethers, Slowing you. Breaking the tether will Stun you', 
     'Bloody hearts appear that apply tethers, Slowing you. Breaking the tether will Stun you and cause you to become vulnerable to damage for a duration', 
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/e/e6/Heart_Tethers_Ultimatum.png'),
    (12, 'Impending Doom', 2, TRUE, False, False, 
     'Rings of Doom appear on the ground which grow over time, exploding for Physical damage once they reach a maximum area', 
     'Rings and circles of Doom appear on the ground which grow over time, exploding for Physical damage once they reach a maximum area', 
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/f/fd/Impending_Doom_Ultimatum.png'),
    (13, 'Lessened Reach', 1, TRUE, False, False, 
     '50% less Area of Effect and Projectile Speed', 
     '',
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/5/5b/Lessened_Reach_Ultimatum.png'),
    (14, 'Lethal Rare Monsters', 1, TRUE, False, False, 
     'Rare Monsters have 1 additional Modifier 30% increased Rare Monsters', 
     '',
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/4/47/Lethal_Rare_Monsters_Ultimatum.png'),
    (15, 'Monster Speed', 1, TRUE, False, False, 
     'Monsters gain 20% increased Skill Speed', 
     '',
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/0/00/Monster_Speed_Ultimatum.png'),
    (16, 'Occasional Impotence', 1, TRUE, False, False, 
     'You and your Minions deal no damage for 2 seconds every 8 seconds', 
     '',
     '',
     False, 
     'https://www.poe2wiki.net/images/a/ad/Occasional_Impotence_Ultimatum.png'),
    (17, 'Petrification Statues', 2, TRUE, TRUE, False, 
     'Challenge area contains several statues that Petrify you if you stand within their gaze for a duration', 
     'Challenge area contains several statues that Petrify you for a long duration if you stand within their gaze for a short duration', 
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/4/4d/Petrification_Statues_Ultimatum.png'),
    (18, 'Random Projectiles', 1, TRUE, False, False, 
     'Your Projectiles fly in random directions Monsters fire additional Projectiles', 
     '',
     '', 
     False, 
     'https://www.poe2wiki.net/images/4/46/Random_Projectiles_Ultimatum.png'),
    (19, 'Reduced Recovery', 2, TRUE, TRUE, False, 
     '40% reduced Life, Mana, and Energy Shield Recovery Rate', 
     '75% reduced Life, Mana, and Energy Shield Recovery Rate', 
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/b/be/Reduced_Recovery_Ultimatum.png'),
    (20, 'Reduced Resistances', 2, TRUE, TRUE, False, 
     '-15% to Elemental Resistances and -10% to Maximum Elemental Resistances', 
     '-30% to Elemental Resistances and -20% to Maximum Elemental Resistances', 
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/7/7f/Reduced_Resistances_Ultimatum.png'),
    (21, 'Resistant Monsters', 1, TRUE, False, False, 
     'Monsters have +40% to all Resistances', 
     '',
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/6/6e/Resistant_Monsters_Ultimatum.png'),
    (22, 'Shielding Monsters', 1, TRUE, False, False, 
     'Monsters are protected by Energy Shield', 
     '',
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/d/db/Shielding_Monsters_Ultimatum.png'),
    (23, 'Shocking Turrets', 2, TRUE, False, False, 
     'Challenge area contains turrets that will periodically fire Lightning Projectiles ahead', 
     'Challenge area contains turrets that will periodically fire a wave of Lightning Projectiles ahead', 
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/c/c2/Shocking_Turrets_Ultimatum.png'),
    (24, 'Stalking Shade', 3, TRUE, False, False, 
     'An invulnerable shade stalks you, inflicting Ruin with its Melee hits Fail the Trials on reaching 7 Ruin', 
     'An invulnerable shade stalks you, gaining speed and inflicting Ruin with Melee and Projectile hits Fail the Trials on reaching 7 Ruin', 
     'An invulnerable shade stalks you, gaining further speed and inflicting Ruin with powerful Melee and Projectile hits Fail the Trials on reaching 7 Ruin',
     TRUE, 
     'https://www.poe2wiki.net/images/5/54/Stalking_Shade_Ultimatum.png'),
    (25, 'Stormcaller Runes', 3, TRUE, TRUE, TRUE, 
     'Runes will appear that will call deadly Lightning storms if you remain in them', 
     'Large runes will appear that will call deadly Lightning storms if you remain in them', 
     'Many large runes will appear that will call deadly Lightning storms if you remain in them',
     TRUE, 
     'https://www.poe2wiki.net/images/6/6b/Stormcaller_Runes_Ultimatum.png'),
    (26, 'Temple Traps', 2, TRUE, TRUE, False, 
     'Challenge area contains spikes that deal Physical damage to those who step on them', 
     'Challenge area contains many spikes that deal Physical damage to those who step on them', 
     '',
     False, 
     'https://www.poe2wiki.net/images/5/51/Temple_Traps_Ultimatum.png'),
    (27, 'Time Paradox', 1, TRUE, False, False, 
     'Buffs expire three times faster and Debuffs expire three times slower', 
     '',
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/3/30/Time_Paradox_Ultimatum.png'),
    (28, 'Toxic Monsters', 1, TRUE, False, False, 
     'Monster Hits always inflict Bleeding and Poison', 
     '',
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/0/04/Toxic_Monsters_Ultimatum.png'),
    (29, 'Unstoppable Monsters', 1, TRUE, False, False, 
     'Monsters cannot be Slowed or Stunned', 
     '',
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/3/3e/Unstoppable_Monsters_Ultimatum.png'),
    (30, 'Vaal Omnitect', 3, TRUE, TRUE, TRUE, 
     'An ancient Vaal machination will deploy attacks against nearby intruders', 
     'An ancient Vaal machination will deploy an array of attacks against nearby intruders', 
     'An ancient Vaal machination will deploy a powerful array of attacks against nearby intruders',
     TRUE, 
     'https://www.poe2wiki.net/images/7/75/Vaal_Omnitect_Ultimatum.png'),
    (31, 'Volatile Fiends', 1, TRUE, False, False, 
     'Monsters release deadly Volatiles on death. Rare monsters leave larger ones', 
     '',
     '',
     TRUE, 
     'https://www.poe2wiki.net/images/9/90/Volatile_Fiends_Ultimatum.png');