CREATE DATABASE IF NOT EXISTS socketables;
USE socketables;

CREATE TABLE IF NOT EXISTS socketables (
    id INT AUTO_INCREMENT PRIMARY KEY,
    socketable_name VARCHAR(255) NOT NULL,
    item_slots VARCHAR(255) NOT NULL,
    martial_effect VARCHAR(255),
    caster_effect VARCHAR(255),
    sceptre_effect VARCHAR(255),
    armour_effect VARCHAR(255),
    helmet_effect VARCHAR(255),
    body_effect VARCHAR(255),
    gloves_effect VARCHAR(255),
    boots_effect VARCHAR(255),
    socket_type VARCHAR(255) NOT NULL
);

INSERT INTO socketables (socketable_name, item_slots, martial_effect, caster_effect, sceptre_effect, armour_effect, helmet_effect, body_effect, gloves_effect, boots_effect, socket_type) VALUES
('Iron Rune', 'martial,caster,armour', '25% increased Physical Damage', '30% increased Spell Damage', '', '25% increased Armour, Evasion and Energy Shield', '', '', '', '', 'Rune'),
('Desert Rune', 'martial,caster,armour', 'Adds 13 to 16 Fire Damage', 'Gain 12% of Damage as Extra Fire Damage', '', '+14% to Fire Resistance', '', '', '', '', 'Rune'),
('Glacial Rune', 'martial,caster,armour', 'Adds 9 to 15 Cold Damage', 'Gain 12% of Damage as Extra Cold Damage', '', '+14% to Cold Resistance', '', '', '', '', 'Rune'),
('Storm Rune', 'martial,caster,armour', 'Adds 1 to 30 Lightning Damage', 'Gain 12% of Damage as Extra Lightning Damage', '', '+14% to Lightning Resistance', '', '', '', '', 'Rune'),
('Body Rune', 'martial,caster,armour', 'Leeches 3% of Physical Damage as Life', '+35 to maximum Energy Shield', '', '+40 to maximum Life', '', '', '', '', 'Rune'),
('Mind Rune', 'martial,caster,armour', 'Leeches 2.5% of Physical Damage as Mana', '+35 to maximum Mana', '', '+35 to maximum Mana', '', '', '', '', 'Rune'),
('Rebirth Rune', 'martial,caster,armour', 'Gain 30 Life per Enemy Killed', '18% increased Energy Shield Recharge Rate', '', 'Regenerate 0.35% of maximum Life per second', '', '', '', '', 'Rune'),
('Inspiration Rune', 'martial,caster,armour', 'Gain 24 Mana per Enemy Killed', '24% increased Mana Regeneration Rate', '', '18% increased Mana Regeneration Rate', '', '', '', '', 'Rune'),
('Stone Rune', 'martial,caster,armour', 'Causes 30% increased Stun Buildup', 'Gain additional Stun Threshold equal to 14% of maximum Energy Shield', '', '+50 to Stun Threshold', '', '', '', '', 'Rune'),
('Vision Rune', 'martial,caster,armour', '+110 to Accuracy Rating', '24% increased Critical Hit Chance for Spells', '', '12% increased Life and Mana Recovery from Flasks', '', '', '', '', 'Rune'),
('Robust Rune', 'martial,caster,armour', '+10 to Strength', '+10 to Strength', '', '+10 to Strength', '', '', '', '', 'Rune'),
('Adept Rune', 'martial,caster,armour', '+10 to Dexterity', '+10 to Dexterity', '', '+10 to Dexterity', '', '', '', '', 'Rune'),
('Resolve Rune', 'martial,caster,armour', '+10 to Intelligence', '+10 to Intelligence', '', '+10 to Intelligence', '', '', '', '', 'Rune'),

('Farrul''s Rune of the Hunt', 'martial', '50% increased Attack Damage against Rare or Unique Enemies', '', '', '', '', '', '', '', 'Rune'),
('Thane Myrk''s Rune of Summer', 'martial', 'Adds 23 to 34 Fire Damage', '', '', '', '', '', '', '', 'Rune'),
('Lady Hestra''s Rune of Winter', 'martial', 'Adds 19 to 28 Cold Damage', '', '', '', '', '', '', '', 'Rune'),
('Thane Leld''s Rune of Spring', 'martial', 'Adds 1 to 60 Lightning Damage', '', '', '', '', '', '', '', 'Rune'),
('Fenumus'' Rune of Agony', 'martial,caster', 'Gain 13% of Damage as Extra Chaos Damage', 'Gain 13% of Damage as Extra Chaos Damage', '', '', '', '', '', '', 'Rune'),
('Thane Girt''s Rune of Wildness', 'caster', '', '25% chance for Spell Skills to fire 2 additional Projectiles', '', '', '', '', '', '', 'Rune'),
('Hedgewitch Assandra''s Rune of Wisdom', 'caster', '', '+1 to Level of all Spell Skills', '', '', '', '', '', '', 'Rune'),
('Saqawal''s Rune of the Sky', 'martial,caster', 'Gain 6% of Damage as Extra Damage of all Elements', 'Gain 6% of Damage as Extra Damage of all Elements', '', '', '', '', '', '', 'Rune'),
('The Greatwolf''s Rune of Willpower', 'body_armour', '', '', '', '', '', '10% of Damage is taken from Mana before Life', '', '', 'Rune'),
('Craiceann''s Rune of Recovery', 'body_armour', '', '', '', '', '', '50% increased Energy Shield Recharge Rate', '', '', 'Rune'),
('Craiceann''s Rune of Warding', 'body_armour', '', '', '', '', '', '40% reduced effect of Curses on you', '', '', 'Rune'),
('Countess Seske''s Rune of Archery', 'bow', 'Bow Attacks fire an additional Arrow', '', '', '', '', '', '', '', 'Rune'),
('Saqawal''s Rune of Erosion', 'helmet', '', '', '', '', '20% increased Exposure Effect', '', '', '', 'Rune'),
('Saqawal''s Rune of Memory', 'helmet', '', '', '', '', '2% increased Experience gain', '', '', '', 'Rune'),
('The Greatwolf''s Rune of Claws', 'gloves', '', '', '', '', '', '', 'Adds 5 to 12 Physical Damage to Attacks', '', 'Rune'),
('Courtesan Mannan''s Rune of Cruelty', 'gloves', '', '', '', '', '', '', '15% increased Magnitude of Damaging Ailments you inflict', '', 'Rune'),
('Thane Grannell''s Rune of Mastery', 'gloves', '', '', '', '', '', '', '20% increased Magnitude of Non-Damaging Ailments you inflict', '', 'Rune'),
('Fenumus'' Rune of Spinning', 'gloves', '', '', '', '', '', '', '8% increased Cast Speed', '', 'Rune'),
('Fenumus'' Rune of Draining', 'gloves', '', '', '', '', '', '', '20% increased Effect of Withered', '', 'Rune'),
('Farrul''s Rune of Grace', 'boots', '', '', '', '', '', '', '', '6% reduced Movement Speed Penalty from using Skills while moving', 'Rune'),
('Farrul''s Rune of the Chase', 'boots', '', '', '', '', '', '', '', '5% increased Movement Speed', 'Rune'),

('Soul Core of Topotante', 'martial,armour', 'Attacks with this Weapon Penetrate 15% Elemental Resistances', '', '', '15% increased Elemental Ailment Threshold', '', '', '', '', 'Core'),
('Soul Core of Tacati', 'martial,armour', '15% chance to Poison on Hit with this weapon', '', '', '+11% to Chaos Resistance', '', '', '', '', 'Core'),
('Soul Core of Opiloti', 'martial,armour', '15% chance to cause Bleeding on Hit', '', '', '10% increased Charm Charges gained', '', '', '', '', 'Core'),
('Soul Core of Jiquani', 'martial,armour', 'Recover 2% of maximum Life on Kill', '', '', '2% increased maximum Life', '', '', '', '', 'Core'),
('Soul Core of Zalatl', 'martial,armour', 'Recover 2% of maximum Mana on Kill', '', '', '2% increased maximum Mana', '', '', '', '', 'Core'),
('Soul Core of Citaqualotl', 'martial,armour', '30% increased Elemental Damage with Attacks', '', '', '+5% to all Elemental Resistances', '', '', '', '', 'Core'),
('Soul Core of Puhuarte', 'martial,armour', '30% increased chance to Ignite', '', '', '+1% to Maximum Fire Resistance', '', '', '', '', 'Core'),
('Soul Core of Tzamoto', 'martial,armour', '20% increased Freeze Buildup', '', '', '+1% to Maximum Cold Resistance', '', '', '', '', 'Core'),
('Soul Core of Xopec', 'martial,armour', '30% increased chance to Shock', '', '', '+1% to Maximum Lightning Resistance', '', '', '', '', 'Core'),
('Soul Core of Quipolatl', 'martial,armour', '5% increased Attack Speed', '', '', '10% reduced Slowing Potency of Debuffs on You', '', '', '', '', 'Core'),
('Soul Core of Ticaba', 'martial,armour', '+12% to Critical Damage Bonus', '', '', 'Hits against you have 10% reduced Critical Damage Bonus', '', '', '', '', 'Core'),
('Soul Core of Atmohua', 'martial,armour', 'Convert 20% of Requirements to Strength', '', '', 'Convert 20% of Requirements to Strength', '', '', '', '', 'Core'),
('Soul Core of Cholotl', 'martial,armour', 'Convert 20% of Requirements to Dexterity', '', '', 'Convert 20% of Requirements to Dexterity', '', '', '', '', 'Core'),
('Soul Core of Zantipi', 'martial,armour', 'Convert 20% of Requirements to Intelligence', '', '', 'Convert 20% of Requirements to Intelligence', '', '', '', '', 'Core'),
('Soul Core of Azcapa', 'martial,armour', '+15 to Spirit', '', '', '5% increased Quantity of Gold Dropped by Slain Enemies', '', '', '', '', 'Core'),

('Atmohua''s Soul Core of Retreat', 'body_armour', '', '', '', '', '', '30% faster start of Energy Shield Recharge', '', '', 'Core'),
('Hayoxi''s Soul Core of Heatproofing', 'body_armour', '', '', '', '', '', '20% of Armour also applies to Cold Damage taken from Hits', '', '', 'Core'),
('Zalatl''s Soul Core of Insulation', 'body_armour', '', '', '', '', '', '20% of Armour also applies to Lightning Damage taken from Hits', '', '', 'Core'),
('Topotante''s Soul Core of Dampening', 'body_armour', '', '', '', '', '', '20% of Armour also applies to Fire Damage taken from Hits', '', '', 'Core'),
('Opiloti''s Soul Core of Assault', 'martial,caster', '50% chance when you gain a Frenzy Charge to gain an additional Frenzy Charge', '50% chance when you gain a Frenzy Charge to gain an additional Frenzy Charge', '', '', '', '', '', '', 'Core'),
('Guatelitzi''s Soul Core of Endurance', 'martial,caster', '50% chance when you gain a Endurance Charge to gain an additional Endurance Charge', '50% chance when you gain a Endurance Charge to gain an additional Endurance Charge', '', '', '', '', '', '', 'Core'),
('Xopec''s Soul Core of Power', 'martial,caster', '50% chance when you gain a Power Charge to gain an additional Power Charge', '50% chance when you gain a Power Charge to gain an additional Power Charge', '', '', '', '', '', '', 'Core'),
('Xipocado''s Soul Core of Dominion', 'caster,sceptre', '', 'Minions deal 40% increased Damage with Command Skills', 'Minions deal 40% increased Damage with Command Skills', '', '', '', '', '', 'Core'),
('Citaqualotl''s Soul Core of Foulness', 'martial', 'Adds 13 to 19 Chaos damage', '', '', '', '', '', '', '', 'Core'),
('Cholotl''s Soul Core of War', 'bow', '20% increased Projectile Speed', '', '', '', '', '', '', '', 'Core'),
('Tacati''s Soul Core of Affliction', 'helmet', '', '', '', '', 'Enemies you Curse have -4% to Chaos Resistance', '', '', '', 'Core'),
('Quipolatl''s Soul Core of Flow', 'helmet', '', '', '', '', '8% increased Skill Effect Duration \n 8% increased Cooldown Recovery Rate', '', '', '', 'Core'),
('Tzamoto''s Soul Core of Ferocity', 'helmet', '', '', '', '', '+4 to Maximum Rage', '', '', '', 'Core'),
('Uromoti''s Soul Core of Attenuation', 'boots', '', '', '', '', '', '', '', '15% increased Curse Duration \n 15% increased Poison Duration', 'Core'),
('Estazunti''s Soul Core of Convalescence', 'helmet,boots', '', '', '', '', '6% of Damage taken Recouped as Life', '', '', '10% increased speed of Recoup Effects', 'Core'),

('Serpent Talisman', 'sceptre,gloves', '', '', 'Allies in your Presence have 8% increased Attack Speed', '', '', '', '5% increased Curse Magnitudes', '', 'Talisman_Blue'),
('Primate Talisman', 'sceptre,helmet', '', '', 'Allies in your Presence deal 30% increased Damage', '', 'Minions have 12% increased maximum Life', '', '', '', 'Talisman_Blue'),
('Owl Talisman', 'sceptre,boots', '', '', 'Allies in your Presence have 8% increased Cast Speed', '', '', '', '', '5% increased Cooldown Recovery Rate', 'Talisman_Blue'),
('Cat Talisman', 'sceptre,boots', '', '', 'Allies in your Presence have 14% increased Critical Hit Chance', '', '', '', '', 'Hits against you have 15% reduced Critical Damage Bonus', 'Talisman_Yellow'),
('Wolf Talisman', 'sceptre,gloves', '', '', 'Allies in your Presence have 14% increased Critical Damage Bonus', '', '', '', '10% increased Magnitude of Bleeding you inflict', '', 'Talisman_Yellow'),
('Stag Talisman', 'sceptre,helmet', '', '', 'Allies in your Presence have +100 to Accuracy Rating', '', '8% increased Exposure Effect', '', '', '', 'Talisman_Yellow'),
('Boar Talisman', 'sceptre,gloves', '', '', 'Allies in your Presence Regenerate 8 Life per second', '', '', '', 'Gain 1 Rage on Melee Hit', '', 'Talisman_Purple'),
('Bear Talisman', 'sceptre,helmet', '', '', 'Allies in your Presence deal 12 to 18 added Attack Physical Damage', '', '8% increased Area of Effect', '', '', '', 'Talisman_Purple'),
('Ox Talisman', 'sceptre,boots', '', '', 'Allies in your Presence have +8% to all Elemental Resistances', '', '', '', '', '20% increased Presence Area of Effect', 'Talisman_Purple'),
('Rabbit Talisman', 'sceptre,body_armour', '', '', '10% increased Spirit', '', '', '8% increased Rarity of Items found', '', '', 'Talisman_Orange'),
('Fox Talisman', 'sceptre,body_armour', '', '', '20% increased Presence Area of Effect', '', '', '+2% to Quality of all Skills', '', '', 'Talisman_Orange'),

('Rune of Leadership', 'martial,armour', 'Minions gain 10% of their Physical Damage as Extra Lightning Damage', '', '', 'Minions take 10% of Physical Damage as Lightning Damage', '', '', '', '', 'Rune'),
('Rune of Tithing', 'martial,armour', 'Meta Skills gain 10% increased Energy', '', '', '1 to 100 Lightning Thorns damage', '', '', '', '', 'Rune'),

('Talisman of Thruldana', 'martial', '25% reduced Poison Duration \n Targets can be affected by +1 of your Poisons at the same time', '', '', '', '', '', '', '', 'Talisman_Blue'),
('Talisman of Maxarius', 'body_armour', '', '', '', '', '', '+1 Charm Slot', '', '', 'Talisman_Yellow'),
('Talisman of Eeshta', 'helmet', '', '', '', '', '6% reduced Cost of Skills', '', '', '', 'Talisman_Blue'),
('Talisman of Egrin', 'helmet', '', '', '', '', 'Enemies you Curse take 5% increased Damage', '', '', '', 'Talisman_Yellow'),
('Talisman of Ralakesh', 'helmet', '', '', '', '', 'Minions have 5% reduced Reservation', '', '', '', 'Talisman_Blue'),
('Talisman of Sirrius', 'gloves', '', '', '', '', '', '', '8% increased Attack Speed', '', 'Talisman_Yellow'),
('Talisman of Grold', 'gloves', '', '', '', '', '', '', 'Skills which Empower an Attack have 15% chance to not count that Attack', '', 'Talisman_Purple'),

('Rune of Alacrity', 'martial,armour', '8% increased Skill Speed', '', '', 'Debuffs on you expire 8% faster', '', '', '', '', 'Rune'),
('Rune of Nobility', 'martial,armour', 'Attacks with this Weapon have 10% chance to inflict Lightning Exposure', '', '', '10% reduced effect of Shock on you', '', '', '', '', 'Rune');