/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoomsImport } from './routes/rooms'
import { Route as RewardsImport } from './routes/rewards'
import { Route as MonstersImport } from './routes/monsters'
import { Route as ModifiersImport } from './routes/modifiers'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RoomsRoute = RoomsImport.update({
  path: '/rooms',
  getParentRoute: () => rootRoute,
} as any)

const RewardsRoute = RewardsImport.update({
  path: '/rewards',
  getParentRoute: () => rootRoute,
} as any)

const MonstersRoute = MonstersImport.update({
  path: '/monsters',
  getParentRoute: () => rootRoute,
} as any)

const ModifiersRoute = ModifiersImport.update({
  path: '/modifiers',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/modifiers': {
      preLoaderRoute: typeof ModifiersImport
      parentRoute: typeof rootRoute
    }
    '/monsters': {
      preLoaderRoute: typeof MonstersImport
      parentRoute: typeof rootRoute
    }
    '/rewards': {
      preLoaderRoute: typeof RewardsImport
      parentRoute: typeof rootRoute
    }
    '/rooms': {
      preLoaderRoute: typeof RoomsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ModifiersRoute,
  MonstersRoute,
  RewardsRoute,
  RoomsRoute,
])

/* prettier-ignore-end */
